spring:

  application:
    name: WebApp

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:admindb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  docker:
    compose:
      enabled: false

  h2:
    console:
      enabled: true
